networks:
  bot:
    driver: bridge

services:
  bot:
    container_name: bot
    # image: user/name:tag
    env_file: .env
    profiles:
      - prod
    networks:
      - bot
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./certs:/usr/src/app/certs
      - ./logs:/usr/src/app/logs

  bot-dev:
    container_name: bot-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      PYTHONPATH: /usr/src/app
    profiles:
      - dev
    networks:
      - bot
    volumes:
      - ./src:/usr/src/app/src
      - ./alembic.ini:/usr/src/app/alembic.ini
      - ./alembic:/usr/src/app/alembic
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17.4-alpine
    container_name: bot-postgres
    networks:
      - bot
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bot
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username=$$POSTGRES_USER --dbname bot
      start_period: 10s
      start_interval: 1s
    profiles:
      - dev
      - prod
      - alembic

  redis:
    image: redis:7.4.2-alpine
    container_name: bot-redis
    networks:
      - bot
    volumes:
      - ./redis_data:/data
    profiles:
      - dev
      - prod
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      start_period: 10s
      start_interval: 1s

  alembic:
    build:
      context: .
      dockerfile: Dockerfile.alembic
    profiles:
      - alembic
    env_file: .env
    networks:
      - bot
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./alembic:/usr/src/app/alembic
    environment:
      MESSAGE: ${MESSAGE}
