FROM python:3.13.2-alpine

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENV PYTHONPATH=/usr/src/app

CMD sh -c "python -u ./src/wait_for_db.py && alembic upgrade head && python -u src/main.py"
