FROM python:3.13.2-alpine

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENV PYTHONPATH=/usr/src/app

CMD alembic revision --autogenerate -m "$MESSAGE" && alembic upgrade head
