FROM python:3.13.2-alpine

RUN pip install --no-cache-dir watchdog

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY alembic alembic
COPY alembic.ini .

ENV PYTHONPATH=/usr/src/app

CMD sh -c "python -u ./src/wait_for_db.py && alembic upgrade head && alembic current && watchmedo auto-restart --patterns="*.py" --recursive --interval 5 -- python -u src/main.py"
