FROM python:3.13.2-alpine

RUN apk update && apk add nodejs
RUN pip install ruff pyright

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY . .

CMD sh -c "ruff check --extend-select I --output-format=github && pyright"
