FROM python:3.13.2-alpine

RUN pip install --no-cache-dir watchdog

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/usr/src/app

CMD alembic upgrade head && alembic current && watchmedo auto-restart --patterns="*.py" --recursive --interval 5 -- python -u src/main.py
