"""Create User and Blocker tables

Revision ID: 6d7f4c733dea
Revises: 
Create Date: 2025-04-02 13:50:02.091497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7f4c733dea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_user_account_chat_id'), 'user_account', ['chat_id'], unique=False)
    op.create_table('blocker',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.chat_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_blocker_message_id'), 'blocker', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocker_message_id'), table_name='blocker')
    op.drop_table('blocker')
    op.drop_index(op.f('ix_user_account_chat_id'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
