apiVersion: v1
kind: Service
metadata:
  name: bot-podname
  labels:
    app: bot
    component: main
spec:
  ports:
    - port: 80
      targetPort: podname
  selector:
    app: bot
    component: main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    app: bot
    component: main
spec:
  selector:
    matchLabels:
      app: bot
      component: main
  template:
    metadata:
      labels:
        app: bot
        component: main
    spec:
      containers:
        - name: bot
          image: coder80/template-bot:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: secret
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: !!str 5432
            - name: DB_TIMEOUT
              value: !!str 10
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 3000
              name: podname
