apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume
  labels:
    app: bot
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: template-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: bot
    component: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: bot
    component: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: bot
    component: postgres
spec:
  selector:
    matchLabels:
      app: bot
      component: postgres
  template:
    metadata:
      labels:
        app: bot
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-volume
      containers:
        - name: postgres
          image: postgres:17.4-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
              name: postgres
