apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume
  labels:
    app: bot
    component: redis
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: bot
    component: redis
spec:
  ports:
    - port: 6379
      targetPort: redis
  selector:
    app: bot
    component: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: bot
    component: redis
spec:
  selector:
    matchLabels:
      app: bot
      component: redis
  template:
    metadata:
      name: redis
      labels:
        app: bot
        component: redis
    spec:
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-volume
      containers:
        - name: redis
          image: redis:7.4.2-alpine
          volumeMounts:
            - name: redis-volume
              mountPath: /data
          ports:
            - containerPort: 6379
              name: redis
