name: Deploy

run-name: Deploy ${{github.sha}}

on:
  workflow_run:
    workflows: [Lint]
    branches: [main]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo $DOCKER_TOKEN | docker login -u coder80 --password-stdin
        env:
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      - name: Build container
        run: docker build -t coder80/template-bot:$SHA -f Dockerfile.prod .
        env:
          SHA: ${{github.sha}}
      - name: Push to Docker Hub
        run: docker push coder80/template-bot:$SHA
        env:
          SHA: ${{github.sha}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Vostro
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set kubectl config
        run: echo $KUBECTL_CONFIG > ~/.kube/config
        env:
          KUBECTL_CONFIG: ${{secrets.KUBECTL}}

      - name: Test cluster connection
        run: kubectl cluster-info

      - name: Deploy
        run: kubectl set image deployments/bot bot=coder80/template-bot:sha
        env:
          SHA: ${{github.sha}}
